default:
  tags:
    - test

stages:
    - extend-stage


Extended Job:
    stage: extend-stage
    script:
     - var1="Oleg"
     - var2="14"
     - echo "name=$var1\nage=$var2\ncity=Los Angeles\ncountry='345345'\nhasCar=true >" ./local.properties
     - cat local.properties
    artifacts:
      paths:
        - local.properties
