default:
  tags:
    - test

cache: 
      when: on_failure
      paths:
        - some.txt

stages:
    - extend-stage

.mainLogic:
  stage: extend-stage
  script:
    echo "Var from another job is $VAR1"
    |
      text_file="some.txt"
            if [ -f "$text_file" ]; then
              if [ -s "$text_file" ]; then
                echo $(cat $text_file)
              else
                echo "$text_file is empty"
              fi
              echo "Test ended"
              exit 0
            fi

    var1="Oleg"
    var2="14"
    |
       echo -e "name=$var1
       age=$var2
       city=Perm
       country=345345
       hasCar=true" > ./some.txt
    cat some.txt
    exit 1

ExtendedJob1:
    allow_failure: true
    extends: .mainLogic
    variables: {VAR1: "FirstJob"} 

ExtendedJob:
    allow_failure: true
  
    extends: .mainLogic
    variables: {VAR1: "SecondJob"} 
    
