default:
  tags:
    - test

stages:
    - extend-stage


Extended Job:
    stage: extend-stage
    script:
     - var1="Oleg"
     - var2="14"
     - set -e
     - |
       echo "name=$var1
       age=$var2
       city=Los Angeles
       country='345345'
       hasCar=true >" ./local.properties
     - cat local.properties
    artifacts:
      paths:
        - local.properties
