default:
  tags:
    - test

stages:
    - first
    - extend-stage
    - clear-cache

First Stage:
  stage: first
  script:
    - echo "some logic"

Last Stage:
  stage: clear-cache
  script: 
    - rm -rf some.txt

.extendJob:
    cache: 
      when: on_failure
      paths:
        - some.txt
    allow_failure: true
    script:
      - echo "job var is $VAR"
      - |
        text_file="some.txt"
            if [ -f "$text_file" ]; then
              if [ -s "$text_file" ]; then
                echo $(cat $text_file)
              else
                echo "$text_file is empty"
              fi
              echo "Test ended"
              exit 0
            fi

      - var1="Oleg"
      - var2="14"
      - |
        echo -e "name=$var1
        age=$var2
        city=Perm
        country=345345
        hasCar=true" > ./some.txt
      - cat some.txt
      - exit 1

Job1:
  variables: {VAR: "FirstJob"} 
  stage: extend-stage
  extends: .extendJob
    

Job2:
  variables: {VAR: "SecondJob"} 
  stage: extend-stage
  extends: .extendJob