default:
  tags:
    - test

stages:
    - extend-stage


.extendJob:
    cache: 
      when: on_failure
      paths:
        - $VAR-some.txt
    allow_failure: true
    script:
      - echo "job var is $VAR"
      - |
        text_file="$VAR-some.txt"
            if [ -f "$text_file" ]; then
              if [ -s "$text_file" ]; then
                echo $(cat $text_file) || exit_code=$?
              else
                echo "$text_file is empty"
              fi
              success_var=$(echo $?)
              echo "Test ended with status code $success_var"
                if [ $success_var == 0 ]; then
                  rm -rf "$tests_file"
                  echo "remove cache folder /Users/o.pendrak/cache/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/*"
                  rm -rf "/Users/o.pendrak/cache/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/*"
                  exit 0
                fi
            fi

      - var1="Oleg"
      - var2="14"
      - |
        echo -e "name=$var1
        age=$var2
        city=Perm
        country=345345
        hasCar=true" > ./$VAR-some.txt
      - cat $VAR-some.txt
      - exit 1

Job1:
  variables: {VAR: "FirstJob"} 
  stage: extend-stage
  extends: .extendJob
    

Job2:
  variables: {VAR: "SecondJob"} 
  stage: extend-stage
  extends: .extendJob