default:
  tags:
    - test

stages:
    - extend-stage

.mainLogic:
  script:
    echo "$VAR1 run cache"
    - |
      text_file="some.txt"
            if [ -f "$text_file" ]; then
              if [ -s "$text_file" ]; then
                echo $(cat $text_file)
              else
                echo "$text_file is empty"
              fi
              echo "Test ended"
              exit 0
            fi

     - var1="Oleg"
     - var2="14"
     - |
       echo -e "name=$var1
       age=$var2
       city=Perm
       country=345345
       hasCar=true" > ./some.txt
     - cat some.txt
     - exit 1

ExtendedJob1:
    cache: 
      when: always
      paths:
        - some.txt
    allow_failure: true
    stage: extend-stage
    extends: .mainLogic
    variables: {VAR1: "FirstJob"} 

ExtendedJob1:
    cache: 
      when: always
      paths:
        - some.txt
    allow_failure: true
    stage: extend-stage
    extends: .mainLogic
    variables: {VAR1: "SecondJob"} 
    
