default:
  tags:
    - test

stages:
    - extend-stage


Extended Job:
    stage: extend-stage
    script:
     - var1="Oleg"
     - var2="14"
     - echo -e "name=$var1\n
      age=$var2\n
      city=Los Angeles\n
      country=345345\n
      hasCar=true" > ./local.properties
     - cat local.properties
    artifacts:
      paths:
        - local.properties
