default:
  tags:
    - test

stages:
    - first
    - extend-stage
    - clear

Clear cache Stage:
  stage: clear
  script: 
    - echo "Cleaning up"
    - rm -rf "/Users/o.pendrak/cache/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/default-protected"
  when: always

First Stage:
  stage: first
  script:
    - echo "some logic"

.extendJob:
    cache: 
      when: on_failure
      paths:
        - $VAR-some.txt
    allow_failure: true
    script:
      - echo "job var is $VAR"
      - |
        text_file="$VAR-some.txt"
            if [ -f "$text_file" ]; then
              if [ -s "$text_file" ]; then
                echo $(cat $text_file) || exit_code=$?
              else
                echo "$text_file is empty"
              fi
              echo "Test ended with status code $exit_code"
              exit $exit_code
            fi

      - var1="Oleg"
      - var2="14"
      - |
        echo -e "name=$var1
        age=$var2
        city=Perm
        country=345345
        hasCar=true" > ./$VAR-some.txt
      - cat $VAR-some.txt
      - exit 1

Job1:
  variables: {VAR: "FirstJob"} 
  stage: extend-stage
  extends: .extendJob
    

Job2:
  variables: {VAR: "SecondJob"} 
  stage: extend-stage
  extends: .extendJob