default:
  tags:
    - test

stages:
    - extend-stage


Extended Job:
    stage: extend-stage
    script:
     - var1="Oleg"
     - var2="14"
     - echo -e
        "name=$var1;
      age=$var2;
      city=Los Angeles;
      country='345345';
      hasCar=true > ./local.properties;"
