default:
  tags:
    - test

stages:
    - extend-stage

.tests:
  script: 
      - echo "my var - $VAR1"
  stage: extend-stage

Extended Job:
    variables: 
        VAR1: OLEG
    stage: extend-stage
    extends: .tests