#Образ для градл
image: gradle:alpine

#image: maven:3.8-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - test

Integration tests with Allure:
  stage: test
  script:
    -  SET JAVA_HOME="E:\JavaTemp\jdk8"
    - ./gradlew clean test
    - ./gradle allureReport
  artifacts:
    paths:
      - build/reports/allure-report/allureReport/*