default:
  tags:
    - test

stages:
    - extend-stage



Extended Job:
    variables: {VAR1: OLEG, VAR2: OLEG2}
    stage: extend-stage
    script: echo "UID is $EMULATOR_UID, name is $NAME, android is $ANDROID"
    parallel:
        matrix:
      - EMULATOR_UID: 1
        NAME: "PIXEL 2"
        ANDROID: "API 29"
      - EMULATOR_UID: 2
        NAME: "PIXEL 3"
        ANDROID: "API 30"
