default:
  tags:
    - test

stages:
    - extend-stage


ExtendedJob:
    allow_failure: true
    stage: extend-stage
    script:
     - curl --location --output artifacts.zip "${CI_API_V4_URL}/projects/38388889/jobs/artifacts/main/download?job=ExtendedJob&private_token=JsGwmoS164-V-aMpq-Sd"
     - unzip artifacts.zip || rm -rf artifacts.zip
     - |
      text_file="some.txt"
            if [ -f "$text_file" ]; then
              if [ -s "$text_file" ]; then
                echo $(cat $text_file)
              else
                echo "$text_file is empty"
              fi
              echo "Test ended"
              exit 0
            fi


     - var1="Oleg"
     - var2="14"
     - |
      echo -e "name=$var1
      age=$var2
      city=Perm
      country=345345
      hasCar=true" > ./some.txt
     - cat some.txt
     - exit 1
    artifacts:
      when: always
      paths:
        - some.txt
